language: elixir
elixir: 1.8
otp_release: 21.2.4
branches:
  only:
  - master
install:
- epmd -daemon
script: make travis
before_script: make travis-init
before_deploy: make travis-deploy
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: IesQBhqckYaysKMgEhfDFzEWIof1Drlk8xwD79hXul1uN67O+3znq1nHKU78G/x0mwxysg7yabe2HSE0f/7wbG7eocIDBtOirSvRb1dVZtTTBYc+UCInCNUtIzzInnU1Ye9GPAQE390vYjyfiZ0juPlPs5yb/YDA7sadauyShBJjaYAXRnx8OgJYcEbR5DcKH5mTutIQNpOlaxTevnHi52lpXd87/IBnw+eWnoxPPTWhuV3Pc4vPi8UJ8NVQTY6ELy/m0W3sHGZ0xXBhD6L8Z+EGy4qysKUu3N3Dj37ivOLJNf550PGmKsGtTcmpvYju5tM2Nw9gWmUB7zs+60HWYElnV6NYLDEhI5utg30fw0hjHpT1D2x2gTeTNh6jk2LuYFuEMMeSW/9dcR0WdwNMDu/lqy1tC5YLUm83JqP4/9xNpWAPtROhMB0bjpHXWOOZwlMxjWFMqfKrIjtWQzcv7I3NrSyrVsk2DQUGbP7xBQ0z7xzLQyMGR8GNRkcqBjo7CCQHfEStsazuHPpuC5eRakxbEdDOlOsAinDYNxSOo90rC8iwy6H9jVUiho682TmLVOTJd5aibfiZlei+nigZNW+hZ1SDFZc+J18GzzOHBmR3unWdehAVcdcfPh6ZYmVkurrgZpHkLiyu9JcZ7J9Xn32NlUdwzuyGYhZavu+hINs=
  file_glob: true
  file: src/_build/releases/*
  on:
    repo: ArcBlock/ex_abci_proto
    branch: master
